---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "app/views/**.erb"
  - "app/models/**.rb"
  - "app/controllers/**.rb"
  - "app/lib/**.rb"
  - "app/public/**.js"
exclude_paths:
- config/
- db/
- test/
- **.ru
- Gemfile
- Rakefile
- **.md
- **.xml
---
engines:
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  eslint:
    enabled: false
  fixme:
    enabled: false
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.rb"
exclude_paths:
- spec/**/*
- coverage/**/*
