language: ruby
rvm:
  - 2.2.2
services:
- postgresql
env:
  - RACK_ENV=test
before_script:
  - psql -c 'create database rush-hour-test' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
# cache: bundler
