language: ruby
rvm:
  - 2.2.2
services:
- postgresql
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database strano_test' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
# cache: bundler
